// <auto-generated />
using System;
using BussinesLogic.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BussinesLogic.Data.Migrations
{
    [DbContext(typeof(UniversityDBContext))]
    [Migration("20220928141500_seeding_tables")]
    partial class seeding_tables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CategoryCourse", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("CoursesId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "CoursesId");

                    b.HasIndex("CoursesId");

                    b.ToTable("CategoryCourse");

                    b.HasData(
                        new
                        {
                            CategoriesId = 1,
                            CoursesId = 1
                        },
                        new
                        {
                            CategoriesId = 3,
                            CoursesId = 2
                        },
                        new
                        {
                            CategoriesId = 2,
                            CoursesId = 3
                        },
                        new
                        {
                            CategoriesId = 1,
                            CoursesId = 4
                        },
                        new
                        {
                            CategoriesId = 1,
                            CoursesId = 5
                        },
                        new
                        {
                            CategoriesId = 2,
                            CoursesId = 6
                        },
                        new
                        {
                            CategoriesId = 3,
                            CoursesId = 6
                        },
                        new
                        {
                            CategoriesId = 4,
                            CoursesId = 6
                        },
                        new
                        {
                            CategoriesId = 1,
                            CoursesId = 7
                        },
                        new
                        {
                            CategoriesId = 3,
                            CoursesId = 7
                        },
                        new
                        {
                            CategoriesId = 4,
                            CoursesId = 7
                        },
                        new
                        {
                            CategoriesId = 2,
                            CoursesId = 8
                        },
                        new
                        {
                            CategoriesId = 2,
                            CoursesId = 9
                        },
                        new
                        {
                            CategoriesId = 3,
                            CoursesId = 9
                        },
                        new
                        {
                            CategoriesId = 4,
                            CoursesId = 9
                        },
                        new
                        {
                            CategoriesId = 6,
                            CoursesId = 10
                        });
                });

            modelBuilder.Entity("Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            Name = "Frontend"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            Name = "Backend"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            Name = "Framework"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            Name = "Testing"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            Name = "Movile"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            Name = "CMS"
                        });
                });

            modelBuilder.Entity("Core.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("nvarchar(280)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            Level = 0,
                            LongDescription = "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?",
                            Name = "Javascript Básico",
                            ShortDescription = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            Level = 2,
                            LongDescription = "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?",
                            Name = "Javascript Avanzado",
                            ShortDescription = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            Level = 1,
                            LongDescription = "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?",
                            Name = "PHP",
                            ShortDescription = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            Level = 0,
                            LongDescription = "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?",
                            Name = "CSS",
                            ShortDescription = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            Level = 2,
                            LongDescription = "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?",
                            Name = "SASS",
                            ShortDescription = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            Level = 1,
                            LongDescription = "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?",
                            Name = "Laravel",
                            ShortDescription = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            Level = 0,
                            LongDescription = "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?",
                            Name = "React",
                            ShortDescription = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            Level = 2,
                            LongDescription = "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?",
                            Name = "C#",
                            ShortDescription = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            Level = 1,
                            LongDescription = "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?",
                            Name = ".NET",
                            ShortDescription = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            Level = 1,
                            LongDescription = "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?",
                            Name = "Wordpress",
                            ShortDescription = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore"
                        });
                });

            modelBuilder.Entity("Core.Entities.Index", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CourseId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("List")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .IsUnique();

                    b.ToTable("Indexes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8572),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            List = "Index Javascript Básico"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8575),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            List = "Index Javascript Avanzado"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8577),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            List = "Index PHP"
                        });
                });

            modelBuilder.Entity("Core.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Birthay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthay = new DateTime(1990, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            LastName = "Sainz",
                            Name = "Andrés",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Birthay = new DateTime(1992, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            LastName = "Lopez",
                            Name = "Chritian",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Birthay = new DateTime(1990, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            LastName = "Ruiz",
                            Name = "Marc",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Birthay = new DateTime(1990, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            LastName = "Test",
                            Name = "Test Admin",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Birthay = new DateTime(1990, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            LastName = "Cruz",
                            Name = "Nicolas",
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            Birthay = new DateTime(1990, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            LastName = "Times",
                            Name = "María",
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            Birthay = new DateTime(1990, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            LastName = "Lopez",
                            Name = "Neri",
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            Birthay = new DateTime(1990, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            LastName = "Vizio",
                            Name = "Pepe",
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            Birthay = new DateTime(1990, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            LastName = "Domingo",
                            Name = "Carlos",
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            Birthay = new DateTime(1990, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            LastName = "Montaña",
                            Name = "Nieves",
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            Birthay = new DateTime(1990, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            LastName = "Sainz",
                            Name = "Mario",
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            Birthay = new DateTime(1990, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            LastName = "Marco",
                            Name = "Chritian",
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            Birthay = new DateTime(1990, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            LastName = "Ruiz",
                            Name = "Lucas",
                            UserId = 13
                        },
                        new
                        {
                            Id = 14,
                            Birthay = new DateTime(1990, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            LastName = "Tetuan",
                            Name = "Karla",
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            Birthay = new DateTime(1990, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            LastName = "Cruz",
                            Name = "Maria",
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            Birthay = new DateTime(1990, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            LastName = "Luengo",
                            Name = "María",
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            Birthay = new DateTime(1990, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            LastName = "Plaza",
                            Name = "Nerea",
                            UserId = 17
                        },
                        new
                        {
                            Id = 18,
                            Birthay = new DateTime(1990, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            LastName = "Montes",
                            Name = "Pepe",
                            UserId = 18
                        },
                        new
                        {
                            Id = 19,
                            Birthay = new DateTime(1990, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            LastName = "Pueblo",
                            Name = "Carlos",
                            UserId = 19
                        },
                        new
                        {
                            Id = 20,
                            Birthay = new DateTime(1990, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            IsDeleted = false,
                            LastName = "Paz",
                            Name = "Concha",
                            UserId = 20
                        });
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            Email = "andresain@gmail.com",
                            IsDeleted = false,
                            LastName = "Sainz",
                            Name = "Andrés",
                            Password = "saiaie88721",
                            Rol = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            Email = "lopez_ch@gmail.com",
                            IsDeleted = false,
                            LastName = "Lopez",
                            Name = "Chritian",
                            Password = "lopse399al",
                            Rol = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            Email = "marrruiz@gmail.com",
                            IsDeleted = false,
                            LastName = "Ruiz",
                            Name = "Marc",
                            Password = "ruimaer438",
                            Rol = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            Email = "admin@gmail.com",
                            IsDeleted = false,
                            LastName = "Test",
                            Name = "Test Admin",
                            Password = "admin1234",
                            Rol = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            Email = "nico@gmail.com",
                            IsDeleted = false,
                            LastName = "Cruz",
                            Name = "Nicolas",
                            Password = "nicola3847",
                            Rol = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            Email = "mtimes@gmail.com",
                            IsDeleted = false,
                            LastName = "Times",
                            Name = "María",
                            Password = "73992hdj",
                            Rol = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            Email = "nerilop@gmail.com",
                            IsDeleted = false,
                            LastName = "Lopez",
                            Name = "Neri",
                            Password = "jooat528j",
                            Rol = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            Email = "vizipep@gmail.com",
                            IsDeleted = false,
                            LastName = "Vizio",
                            Name = "Pepe",
                            Password = "vizip3883",
                            Rol = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            Email = "domica13@gmail.com",
                            IsDeleted = false,
                            LastName = "Domingo",
                            Name = "Carlos",
                            Password = "1313dom12",
                            Rol = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            Email = "monieve@gmail.com",
                            IsDeleted = false,
                            LastName = "Montaña",
                            Name = "Nieves",
                            Password = "moni525niev",
                            Rol = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            Email = "msainz@gmail.com",
                            IsDeleted = false,
                            LastName = "Sainz",
                            Name = "Mario",
                            Password = "sain28282",
                            Rol = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            Email = "m_chris@gmail.com",
                            IsDeleted = false,
                            LastName = "Marco",
                            Name = "Chritian",
                            Password = "cmr8721",
                            Rol = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            Email = "lucaruiz@gmail.com",
                            IsDeleted = false,
                            LastName = "Ruiz",
                            Name = "Lucas",
                            Password = "ruizlu18822",
                            Rol = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            Email = "katet@gmail.com",
                            IsDeleted = false,
                            LastName = "Tetuan",
                            Name = "Karla",
                            Password = "kkktet282",
                            Rol = 0
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            Email = "cruzima@gmail.com",
                            IsDeleted = false,
                            LastName = "Cruz",
                            Name = "Maria",
                            Password = "maricru828228",
                            Rol = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            Email = "luma@gmail.com",
                            IsDeleted = false,
                            LastName = "Luengo",
                            Name = "María",
                            Password = "luen7262",
                            Rol = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            Email = "nerplaza@gmail.com",
                            IsDeleted = false,
                            LastName = "Plaza",
                            Name = "Nerea",
                            Password = "palz8181",
                            Rol = 1
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            Email = "montespe@gmail.com",
                            IsDeleted = false,
                            LastName = "Montes",
                            Name = "Pepe",
                            Password = "jsajas8",
                            Rol = 1
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            Email = "puebosss@gmail.com",
                            IsDeleted = false,
                            LastName = "Pueblo",
                            Name = "Carlos",
                            Password = "1323aasdom12",
                            Rol = 1
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2022, 9, 28, 16, 15, 0, 341, DateTimeKind.Local).AddTicks(8180),
                            CreatedBy = "Seeder",
                            Email = "pazcoc@gmail.com",
                            IsDeleted = false,
                            LastName = "Paz",
                            Name = "Concha",
                            Password = "asasppq871",
                            Rol = 1
                        });
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<int>("CoursesId")
                        .HasColumnType("int");

                    b.Property<int>("StudentsId")
                        .HasColumnType("int");

                    b.HasKey("CoursesId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("CourseStudent");

                    b.HasData(
                        new
                        {
                            CoursesId = 1,
                            StudentsId = 1
                        },
                        new
                        {
                            CoursesId = 2,
                            StudentsId = 1
                        },
                        new
                        {
                            CoursesId = 3,
                            StudentsId = 1
                        },
                        new
                        {
                            CoursesId = 1,
                            StudentsId = 2
                        },
                        new
                        {
                            CoursesId = 2,
                            StudentsId = 2
                        },
                        new
                        {
                            CoursesId = 2,
                            StudentsId = 3
                        },
                        new
                        {
                            CoursesId = 5,
                            StudentsId = 3
                        },
                        new
                        {
                            CoursesId = 6,
                            StudentsId = 3
                        },
                        new
                        {
                            CoursesId = 4,
                            StudentsId = 4
                        },
                        new
                        {
                            CoursesId = 5,
                            StudentsId = 4
                        },
                        new
                        {
                            CoursesId = 4,
                            StudentsId = 5
                        },
                        new
                        {
                            CoursesId = 5,
                            StudentsId = 5
                        },
                        new
                        {
                            CoursesId = 2,
                            StudentsId = 6
                        },
                        new
                        {
                            CoursesId = 9,
                            StudentsId = 7
                        },
                        new
                        {
                            CoursesId = 6,
                            StudentsId = 8
                        },
                        new
                        {
                            CoursesId = 7,
                            StudentsId = 8
                        },
                        new
                        {
                            CoursesId = 8,
                            StudentsId = 8
                        },
                        new
                        {
                            CoursesId = 10,
                            StudentsId = 9
                        },
                        new
                        {
                            CoursesId = 4,
                            StudentsId = 9
                        },
                        new
                        {
                            CoursesId = 3,
                            StudentsId = 9
                        },
                        new
                        {
                            CoursesId = 9,
                            StudentsId = 10
                        },
                        new
                        {
                            CoursesId = 1,
                            StudentsId = 11
                        },
                        new
                        {
                            CoursesId = 2,
                            StudentsId = 11
                        },
                        new
                        {
                            CoursesId = 3,
                            StudentsId = 11
                        },
                        new
                        {
                            CoursesId = 1,
                            StudentsId = 12
                        },
                        new
                        {
                            CoursesId = 2,
                            StudentsId = 12
                        },
                        new
                        {
                            CoursesId = 2,
                            StudentsId = 13
                        },
                        new
                        {
                            CoursesId = 5,
                            StudentsId = 13
                        },
                        new
                        {
                            CoursesId = 6,
                            StudentsId = 13
                        },
                        new
                        {
                            CoursesId = 4,
                            StudentsId = 14
                        },
                        new
                        {
                            CoursesId = 5,
                            StudentsId = 14
                        },
                        new
                        {
                            CoursesId = 4,
                            StudentsId = 15
                        },
                        new
                        {
                            CoursesId = 5,
                            StudentsId = 15
                        },
                        new
                        {
                            CoursesId = 2,
                            StudentsId = 16
                        },
                        new
                        {
                            CoursesId = 9,
                            StudentsId = 17
                        });
                });

            modelBuilder.Entity("CategoryCourse", b =>
                {
                    b.HasOne("Core.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Index", b =>
                {
                    b.HasOne("Core.Entities.Course", "Course")
                        .WithOne("Index")
                        .HasForeignKey("Core.Entities.Index", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Core.Entities.Student", b =>
                {
                    b.HasOne("Core.Entities.User", null)
                        .WithOne("Student")
                        .HasForeignKey("Core.Entities.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("Core.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Course", b =>
                {
                    b.Navigation("Index");
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
